name: C/C++ CI

on: [push,pull_request]

jobs:
  build-any:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13]
        out_format: [ANSI, HTML5]
        print: [DEFAULT, ALL_SCRIPTS]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: g++ -std=c++11 -Wall -Wno-unused-function -Werror -DPRINT_${{ matrix.print }} -D${{ matrix.out_format }} list-rooms.cpp -o soe-script-dumper
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: soe-script-dumper_${{ matrix.os }}_${{ matrix.print }}_${{ matrix.out_format }}
        path: soe-script-dumper
        if-no-files-found: error

  build-windows:
    strategy:
      matrix:
        os: [windows-latest]
        out_format: [ANSI, HTML5]
        print: [DEFAULT, ALL_SCRIPTS]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Build (Windows)
      run: cl.exe /DPRINT_${{ matrix.print }} /D${{ matrix.out_format }} /EHsc /WX list-rooms.cpp /link /out:soe-script-dumper.exe
    - name: Upload (Windows)
      uses: actions/upload-artifact@v4
      with:
        name: soe-script-dumper_${{ matrix.os }}_${{ matrix.print }}_${{ matrix.out_format }}
        path: soe-script-dumper.exe
        if-no-files-found: error
